name: build

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Set Context
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: yarn install
      run: yarn install
    - name: build application
      run: yarn build:win
    - name: create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          dist/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}